---
apiVersion: apps/v1
kind: replicaSet
metadata:
  name: ngninx-rs
spec:
  replicas: 3
  selector:
    matchExpressions:
      -
        key: tier
        operator: In
        values:
          - frontend
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
        tier: frontend
      name: nginx-pod
    spec:
      containers:
        -
          image: nginx
          name: nginx-container
          port:
            -
              containerPort: 80
